input_dir: "./data"
name: "PDF Interaction ChatBot"
modelEmbeddings: "sentence-transformers/all-MiniLM-L6-v2"
autoTokenizer: "meta-llama/Llama-2-7b-chat-hf"
autoModelForCausalLM: "meta-llama/Llama-2-7b-chat-hf"
PINECONE_API_KEY: "62e3bbfd-005c-4a66-8f89-7c4093b51a9b"
PINECONE_API_ENV: "gcp-starter"